### ISSUE TITLE
Great Job! Can dmcgb2 support baselines in dmcgb1?

### ISSUE THREAD

**Issue by XiaoWei-i** [aalmuzairee/dmcgb2#1]
Great Job! Can dmcgb2 support baselines in dmcgb1? Thanks a lot.

**Comment by aalmuzairee** [comment]
Thanks! We chose to port over the highest performing baseline (SVEA) and compare against it. However, one can easily port over the other baselines by building on the [algos/drq.py](https://github.com/aalmuzairee/dmcgb2/blob/master/algos/drq.py) baseline. (For SAC: Remove shift aug, for SODA: Add SODA loss, for CURL: Add CURL Loss and so on) Unfortunately, I don't have the bandwidth right now. If you want to support them and create a pull request that would also be great!

**Comment by XiaoWei-i** [comment]
Thank you for your reply!
